package gr.ictpro.mall.model;

// Generated Jan 9, 2016 5:28:52 PM by Hibernate Tools 4.0.0

import gr.ictpro.mall.interceptors.ClientReferenceClass;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calendar generated by hbm2java
 */
@Entity
@Table(name = "calendar")
@ClientReferenceClass(className="gr.ictpro.mall.client.model.vo.Calendar")
public class Calendar implements java.io.Serializable {

    private Integer id;
    private Schedule schedule;
    private User user;
    private Classroom classroom;
    private Date startTime;
    private Date endTime;
    private String description;

    public Calendar() {
    }

    public Calendar(Date startTime, Date endTime, String description) {
	this.startTime = startTime;
	this.endTime = endTime;
	this.description = description;
    }

    public Calendar(Schedule schedule, User user, Classroom classroom, Date startTime, Date endTime, String description) {
	this.schedule = schedule;
	this.user = user;
	this.classroom = classroom;
	this.startTime = startTime;
	this.endTime = endTime;
	this.description = description;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "schedule_id")
    public Schedule getSchedule() {
	return this.schedule;
    }

    public void setSchedule(Schedule schedule) {
	this.schedule = schedule;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    public User getUser() {
	return this.user;
    }

    public void setUser(User user) {
	this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "classroom_id")
    public Classroom getClassroom() {
	return this.classroom;
    }

    public void setClassroom(Classroom classroom) {
	this.classroom = classroom;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time", nullable = false, length = 19)
    public Date getStartTime() {
	return this.startTime;
    }

    public void setStartTime(Date startTime) {
	this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time", nullable = false, length = 19)
    public Date getEndTime() {
	return this.endTime;
    }

    public void setEndTime(Date endTime) {
	this.endTime = endTime;
    }

    @Column(name = "description", nullable = false, length = 255)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

}
