package gr.ictpro.mall.model;

// Generated Dec 13, 2015 3:42:01 PM by Hibernate Tools 4.0.0


import gr.ictpro.mall.interceptors.ClientReferenceClass;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.springframework.flex.core.io.AmfIgnore;

/**
 * Classroom generated by hbm2java
 */
@Entity
@Table(name = "classroom"
	, uniqueConstraints = @UniqueConstraint(columnNames = { "name", "language_code" }))
@ClientReferenceClass(className="gr.ictpro.mall.client.model.vo.Classroom")
public class Classroom implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = -7863051231334929908L;
    
    private Integer id;
    private Language language;
    private String name;
    private String notes;
    private boolean forceUILanguage;
    private boolean disallowUnattendedMeetings;
    private boolean autoApproveUnattendedMeetings;
    private Set<Translation> translations = new HashSet<Translation>(0);
    private Set<Classroomgroup> classroomgroups = new HashSet<Classroomgroup>(0);
    private Set<EmailTranslation> emailTranslations = new HashSet<EmailTranslation>(0);
    private Set<User> students = new HashSet<User>(0);
    private User teacher;
    private Set<Calendar> calendars = new HashSet<Calendar>(0);
    private Set<Schedule> schedules = new HashSet<Schedule>(0);

    public Classroom() {
    }

    public Classroom(String name, boolean forceUILanguage, boolean autoApproveUnattendedMeetings, boolean disallowUnattendedMeetings) {
	this.name = name;
	this.forceUILanguage = forceUILanguage;
	this.disallowUnattendedMeetings = disallowUnattendedMeetings;
	this.autoApproveUnattendedMeetings = autoApproveUnattendedMeetings;
    }

    public Classroom(Language language, String name, String notes, boolean forceUILanguage, Set<Translation> translations,
	    Set<Classroomgroup> classroomgroups, Set<EmailTranslation> emailTranslations, Set<User> students, User teacher, 
	    Set<Calendar> calendars, Set<Schedule> schedules, boolean autoApproveUnattendedMeetings, boolean disallowUnattendedMeetings) {
	this.language = language;
	this.name = name;
	this.notes = notes;
	this.forceUILanguage = forceUILanguage;
	this.translations = translations;
	this.classroomgroups = classroomgroups;
	this.emailTranslations = emailTranslations;
	this.students = students;
	this.calendars = calendars;
	this.schedules = schedules;
	this.disallowUnattendedMeetings = disallowUnattendedMeetings;
	this.autoApproveUnattendedMeetings = autoApproveUnattendedMeetings;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "language_code")
    public Language getLanguage() {
	return this.language;
    }

    public void setLanguage(Language language) {
	this.language = language;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "notes", length = 65535, columnDefinition = "Text")
    public String getNotes() {
	return this.notes;
    }

    public void setNotes(String notes) {
	this.notes = notes;
    }
    
    @Column(name = "disallow_unattended_meetings", nullable = false)
    public boolean isDisallowUnattendedMeetings() {
	return this.disallowUnattendedMeetings;
    }

    public void setDisallowUnattendedMeetings(boolean disallowUnattendedMeetings) {
	this.disallowUnattendedMeetings = disallowUnattendedMeetings;
    }

    @Column(name = "force_ui_language", nullable = false)
    public boolean isForceUILanguage() {
	return this.forceUILanguage;
    }

    public void setForceUILanguage(boolean forceUILanguage) {
	this.forceUILanguage = forceUILanguage;
    }


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "classroom")
    @AmfIgnore
    public Set<Translation> getTranslations() {
	return this.translations;
    }

    @AmfIgnore
    public void setTranslations(Set<Translation> translations) {
	this.translations = translations;
    }

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "classroom_classroomgroup", joinColumns = {
	    @JoinColumn(name = "classroom_id", nullable = false, updatable = false) }, inverseJoinColumns = {
	    @JoinColumn(name = "group_id", nullable = false, updatable = false) })
    public Set<Classroomgroup> getClassroomgroups() {
	return this.classroomgroups;
    }

    public void setClassroomgroups(Set<Classroomgroup> classroomgroups) {
	this.classroomgroups = classroomgroups;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "classroom")
    @AmfIgnore
    public Set<EmailTranslation> getEmailTranslations() {
	return this.emailTranslations;
    }

    @AmfIgnore
    public void setEmailTranslations(Set<EmailTranslation> emailTranslations) {
	this.emailTranslations = emailTranslations;
    }

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "classroom_user", joinColumns = {
	    @JoinColumn(name = "class_id", nullable = false, updatable = false) }, inverseJoinColumns = {
	    @JoinColumn(name = "user_id", nullable = false, updatable = false) })
    public Set<User> getStudents() {
	return this.students;
    }

    public void setStudents(Set<User> students) {
	this.students = students;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "teacher_id")
    public User getTeacher() {
	return this.teacher;
    }

    public void setTeacher(User teacher) {
	this.teacher = teacher;
    }
    
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "classroom")
    public Set<Calendar> getCalendars() {
	return this.calendars;
    }

    public void setSchedules(Set<Schedule> schedules) {
	this.schedules = schedules;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "classroom")
    @AmfIgnore
    public Set<Schedule> getSchedules() {
	return this.schedules;
    }

    public void setCalendars(Set<Calendar> calendars) {
	this.calendars = calendars;
    }

    @Column(name = "auto_approve_unattended_meetings", nullable = false)
    public boolean isAutoApproveUnattendedMeetings() {
	return this.autoApproveUnattendedMeetings;
    }

    public void setAutoApproveUnattendedMeetings(boolean autoApproveUnattendedMeetings) {
	this.autoApproveUnattendedMeetings = autoApproveUnattendedMeetings;
    }
}
