package gr.ictpro.mall.model;

// Generated May 17, 2016 11:56:07 PM by Hibernate Tools 4.0.0


import gr.ictpro.mall.interceptors.ClientReferenceClass;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CourseTemplate generated by hbm2java
 */
@Entity
@Table(name = "course_template")
@ClientReferenceClass(className="gr.ictpro.mall.client.model.vo.CourseTemplate")
public class CourseTemplate implements java.io.Serializable {

    private Integer id;
    private String name;
    private String moodleId;
    private Set<Course> courses = new HashSet<Course>(0);

    public CourseTemplate() {
    }

    public CourseTemplate(String name, String moodleId) {
	this.name = name;
	this.moodleId = moodleId;
    }

    public CourseTemplate(String name, String moodleId, Set<Course> courses) {
	this.name = name;
	this.moodleId = moodleId;
	this.courses = courses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "moodle_id", nullable = false, length = 100)
    public String getMoodleId() {
	return this.moodleId;
    }

    public void setMoodleId(String moodleId) {
	this.moodleId = moodleId;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "courseTemplate")
    public Set<Course> getCourses() {
	return this.courses;
    }

    public void setCourses(Set<Course> courses) {
	this.courses = courses;
    }

}
