package gr.ictpro.mall.model;

// Generated Dec 6, 2015 2:17:59 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmailTranslation generated by hbm2java
 */
@Entity
@Table(name = "email_translation"
	, uniqueConstraints = @UniqueConstraint(columnNames = { "language_code", "email_type" }))
public class EmailTranslation implements java.io.Serializable {

    private Integer id;
    private Language language;
    private EnglishEmail englishEmail;
    private String body;
    private EmailType emailType;
    private String subject;

    public EmailTranslation() {
    }

    public EmailTranslation(Language language, String body, EmailType emailType, String subject) {
	this.language = language;
	this.body = body;
	this.emailType = emailType;
	this.subject = subject;
    }

    public EmailTranslation(Language language, EnglishEmail englishEmail, String body, EmailType emailType,
	    String subject) {
	this.language = language;
	this.englishEmail = englishEmail;
	this.body = body;
	this.emailType = emailType;
	this.subject = subject;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "language_code", nullable = false)
    public Language getLanguage() {
	return this.language;
    }

    public void setLanguage(Language language) {
	this.language = language;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "english_email_id")
    public EnglishEmail getEnglishEmail() {
	return this.englishEmail;
    }

    public void setEnglishEmail(EnglishEmail englishEmail) {
	this.englishEmail = englishEmail;
    }

    @Column(name = "body", nullable = false, length = 65535, columnDefinition="Text")
    public String getBody() {
	return this.body;
    }

    public void setBody(String body) {
	this.body = body;
    }

    @Column(name = "email_type", nullable = false)
    public EmailType getEmailType() {
	return this.emailType;
    }

    public void setEmailType(EmailType emailType) {
	this.emailType = emailType;
    }

    @Column(name = "subject", nullable = false, length = 100)
    public String getSubject() {
	return this.subject;
    }

    public void setSubject(String subject) {
	this.subject = subject;
    }

}
