package gr.ictpro.mall.model;

// Generated Dec 5, 2015 4:26:02 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;
import gr.ictpro.mall.model.EmailType;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name = "email"
	, uniqueConstraints = @UniqueConstraint(columnNames = { "language_code", "email_type" }))
public class Email implements java.io.Serializable {

    private int id;
    private Language language;
    private Email englishEmail;
    private EmailType emailType;
    private String body;
    private String subject;
    private Set<Email> translations = new HashSet<Email>(0);

    public Email() {
    }

    public Email(int id, Language language, EmailType emailType, String body, String subject) {
	this.id = id;
	this.language = language;
	this.emailType = emailType;
	this.body = body;
	this.subject = subject;
    }

    public Email(int id, Language language, Email englishEmail, EmailType emailType, String body, String subject,
	    Set<Email> translations) {
	this.id = id;
	this.language = language;
	this.englishEmail = englishEmail;
	this.emailType = emailType;
	this.body = body;
	this.subject = subject;
	this.translations = translations;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "language_code", nullable = false)
    public Language getLanguage() {
	return this.language;
    }

    public void setLanguage(Language language) {
	this.language = language;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "english_email_id")
    public Email getEnglishEmail() {
	return this.englishEmail;
    }

    public void setEnglishEmail(Email englishEmail) {
	this.englishEmail = englishEmail;
    }

    @Column(name = "email_type", nullable = false, length = 45)
    public EmailType getEmailType() {
	return this.emailType;
    }

    public void setEmailType(EmailType emailType) {
	this.emailType = emailType;
    }

    @Column(name = "body", nullable = false, length = 65535, columnDefinition = "Text")
    public String getBody() {
	return this.body;
    }

    public void setBody(String body) {
	this.body = body;
    }

    @Column(name = "subject", nullable = false, length = 100)
    public String getSubject() {
	return this.subject;
    }

    public void setSubject(String subject) {
	this.subject = subject;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "englishEmail")
    public Set<Email> getTranslations() {
	return this.translations;
    }

    public void setTranslations(Set<Email> translations) {
	this.translations = translations;
    }

}
