package gr.ictpro.mall.model;

// Generated Dec 6, 2015 2:34:12 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EnglishEmail generated by hbm2java
 */
@Entity
@Table(name = "english_email"
	, uniqueConstraints = @UniqueConstraint(columnNames = "email_type"))
public class EnglishEmail implements java.io.Serializable {

    private Integer id;
    private EmailType emailType;
    private String subject;
    private String body;
    private Set<EmailTranslation> emailTranslations = new HashSet<EmailTranslation>(0);

    public EnglishEmail() {
    }

    public EnglishEmail(EmailType emailType, String subject, String body) {
	this.emailType = emailType;
	this.subject = subject;
	this.body = body;
    }

    public EnglishEmail(EmailType emailType, String subject, String body, Set<EmailTranslation> emailTranslations) {
	this.emailType = emailType;
	this.subject = subject;
	this.body = body;
	this.emailTranslations = emailTranslations;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @Column(name = "email_type", unique = true, nullable = false)
    public EmailType getEmailType() {
	return this.emailType;
    }

    public void setEmailType(EmailType emailType) {
	this.emailType = emailType;
    }

    @Column(name = "subject", nullable = false, length = 100)
    public String getSubject() {
	return this.subject;
    }

    public void setSubject(String subject) {
	this.subject = subject;
    }

    @Column(name = "body", nullable = false, length = 65535, columnDefinition="Text")
    public String getBody() {
	return this.body;
    }

    public void setBody(String body) {
	this.body = body;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "englishEmail")
    public Set<EmailTranslation> getEmailTranslations() {
	return this.emailTranslations;
    }

    public void setEmailTranslations(Set<EmailTranslation> emailTranslations) {
	this.emailTranslations = emailTranslations;
    }

}
