package gr.ictpro.mall.model;

// Generated Nov 27, 2015 1:29:22 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EnglishText generated by hbm2java
 */
@Entity
@Table(name = "english_text"
	, uniqueConstraints = @UniqueConstraint(columnNames = "english_text"))
public class EnglishText implements java.io.Serializable {

    private Integer id;
    private String englishText;
    private Set<Translation> translations = new HashSet<Translation>(0);

    public EnglishText() {
    }

    public EnglishText(String englishText) {
	this.englishText = englishText;
    }

    public EnglishText(String englishText, Set<Translation> translations) {
	this.englishText = englishText;
	this.translations = translations;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @Column(name = "english_text", unique = true, nullable = false, length = 65535, columnDefinition="Text")
    public String getEnglishText() {
	return this.englishText;
    }

    public void setEnglishText(String englishText) {
	this.englishText = englishText;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "englishText")
    public Set<Translation> getTranslations() {
	return this.translations;
    }

    public void setTranslations(Set<Translation> translations) {
	this.translations = translations;
    }

}
