package gr.ictpro.mall.model;

// Generated Nov 1, 2015 6:39:42 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language")
public class Language implements java.io.Serializable {

    private String code;
    private String englishName;
    private String localName;
    private Set<StudyClass> studyClasses = new HashSet<StudyClass>(0);

    public Language() {
    }

    public Language(String code, String englishName, String localName) {
	this.code = code;
	this.englishName = englishName;
	this.localName = localName;
    }

    public Language(String code, String englishName, String localName, Set<StudyClass> studyClasses) {
	this.code = code;
	this.englishName = englishName;
	this.localName = localName;
	this.studyClasses = studyClasses;
    }

    @Id
    @Column(name = "code", unique = true, nullable = false, length = 5)
    public String getCode() {
	return this.code;
    }

    public void setCode(String code) {
	this.code = code;
    }

    @Column(name = "english_name", nullable = false, length = 100)
    public String getEnglishName() {
	return this.englishName;
    }

    public void setEnglishName(String englishName) {
	this.englishName = englishName;
    }

    @Column(name = "local_name", nullable = false, length = 100)
    public String getLocalName() {
	return this.localName;
    }

    public void setLocalName(String localName) {
	this.localName = localName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
    public Set<StudyClass> getStudyClasses() {
	return this.studyClasses;
    }

    public void setStudyClasses(Set<StudyClass> studyClasses) {
	this.studyClasses = studyClasses;
    }

}
