package gr.ictpro.mall.model;

// Generated Nov 30, 2015 9:51:50 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language")
public class Language implements java.io.Serializable {

    private String code;
    private String englishName;
    private String localName;
    private Set<StudyClass> studyClasses = new HashSet<StudyClass>(0);
    private Set<Translation> translations = new HashSet<Translation>(0);
    private Set<Email> emails = new HashSet<Email>(0);

    public Language() {
    }

    public Language(String code, String englishName, String localName) {
	this.code = code;
	this.englishName = englishName;
	this.localName = localName;
    }

    public Language(String code, String englishName, String localName, Set<StudyClass> studyClasses,
	    Set<Translation> translations, Set<Email> emails) {
	this.code = code;
	this.englishName = englishName;
	this.localName = localName;
	this.studyClasses = studyClasses;
	this.translations = translations;
	this.emails = emails;
    }

    @Id
    @Column(name = "code", unique = true, nullable = false, length = 5)
    public String getCode() {
	return this.code;
    }

    public void setCode(String code) {
	this.code = code;
    }

    @Column(name = "english_name", nullable = false, length = 100)
    public String getEnglishName() {
	return this.englishName;
    }

    public void setEnglishName(String englishName) {
	this.englishName = englishName;
    }

    @Column(name = "local_name", nullable = false, length = 100)
    public String getLocalName() {
	return this.localName;
    }

    public void setLocalName(String localName) {
	this.localName = localName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
    public Set<StudyClass> getStudyClasses() {
	return this.studyClasses;
    }

    public void setStudyClasses(Set<StudyClass> studyClasses) {
	this.studyClasses = studyClasses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
    public Set<Translation> getTranslations() {
	return this.translations;
    }

    public void setTranslations(Set<Translation> translations) {
	this.translations = translations;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
    public Set<Email> getEmails() {
	return this.emails;
    }

    public void setEmails(Set<Email> emails) {
	this.emails = emails;
    }

}
