package gr.ictpro.mall.model;

// Generated Jun 5, 2016 2:39:07 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MeetingType generated by hbm2java
 */
@Entity
@Table(name = "meeting_type")
public class MeetingType implements java.io.Serializable {

    private Integer id;
    private String clientClass;
    private String url;
    private boolean internalModule;
    private String name;
    private Set<Meeting> meetings = new HashSet<Meeting>(0);

    public MeetingType() {
    }

    public MeetingType(String clientClass, boolean internalModule, String name) {
	this.clientClass = clientClass;
	this.internalModule = internalModule;
	this.name = name;
    }

    public MeetingType(String clientClass, String url, boolean internalModule, String name, Set<Meeting> meetings) {
	this.clientClass = clientClass;
	this.url = url;
	this.internalModule = internalModule;
	this.name = name;
	this.meetings = meetings;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @Column(name = "client_class", nullable = false)
    public String getClientClass() {
	return this.clientClass;
    }

    public void setClientClass(String clientClass) {
	this.clientClass = clientClass;
    }

    @Column(name = "url")
    public String getUrl() {
	return this.url;
    }

    public void setUrl(String url) {
	this.url = url;
    }

    @Column(name = "internalModule", nullable = false)
    public boolean isInternalModule() {
	return this.internalModule;
    }

    public void setInternalModule(boolean internalModule) {
	this.internalModule = internalModule;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "meetingType")
    public Set<Meeting> getMeetings() {
	return this.meetings;
    }

    public void setMeetings(Set<Meeting> meetings) {
	this.meetings = meetings;
    }

}
