package gr.ictpro.mall.model;

// Generated Mar 10, 2016 8:58:08 PM by Hibernate Tools 4.0.0

import gr.ictpro.mall.interceptors.ClientReferenceClass;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Meeting generated by hbm2java
 */
@Entity
@Table(name = "meeting")
@ClientReferenceClass(className="gr.ictpro.mall.client.model.vo.Notification")
public class Meeting implements java.io.Serializable {

    private Integer id;
    private User user;
    private MeetingType meetingType;
    private String name;
    private String password;
    private Date time;
    private Set<MeetingUser> meetingUsers = new HashSet<MeetingUser>(0);

    public Meeting() {
    }

    public Meeting(MeetingType meetingType, String name, String password, Date time) {
	this.meetingType = meetingType;
	this.name = name;
	this.password = password;
	this.time = time;
    }

    public Meeting(User user, MeetingType meetingType, String name, String password, Date time,
	    Set<MeetingUser> meetingUsers) {
	this.user = user;
	this.meetingType = meetingType;
	this.name = name;
	this.password = password;
	this.time = time;
	this.meetingUsers = meetingUsers;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "approved_by")
    public User getUser() {
	return this.user;
    }

    public void setUser(User user) {
	this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "meeting_type_id", nullable = false)
    public MeetingType getMeetingType() {
	return this.meetingType;
    }

    public void setMeetingType(MeetingType meetingType) {
	this.meetingType = meetingType;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "password", nullable = false, length = 45)
    public String getPassword() {
	return this.password;
    }

    public void setPassword(String password) {
	this.password = password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "time", nullable = false, length = 19)
    public Date getTime() {
	return this.time;
    }

    public void setTime(Date time) {
	this.time = time;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "meeting")
    public Set<MeetingUser> getMeetingUsers() {
	return this.meetingUsers;
    }

    public void setMeetingUsers(Set<MeetingUser> meetingUsers) {
	this.meetingUsers = meetingUsers;
    }

}
