package gr.ictpro.mall.model;

// Generated Mar 10, 2016 8:58:08 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MeetingUserId generated by hbm2java
 */
@Embeddable
public class MeetingUserId implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -7561504920285482879L;
    
    private int meetingId;
    private int userId;

    public MeetingUserId() {
    }

    public MeetingUserId(int meetingId, int userId) {
	this.meetingId = meetingId;
	this.userId = userId;
    }

    @Column(name = "meeting_id", nullable = false)
    public int getMeetingId() {
	return this.meetingId;
    }

    public void setMeetingId(int meetingId) {
	this.meetingId = meetingId;
    }

    @Column(name = "user_id", nullable = false)
    public int getUserId() {
	return this.userId;
    }

    public void setUserId(int userId) {
	this.userId = userId;
    }

    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof MeetingUserId))
	    return false;
	MeetingUserId castOther = (MeetingUserId) other;

	return (this.getMeetingId() == castOther.getMeetingId())
		&& (this.getUserId() == castOther.getUserId());
    }

    public int hashCode() {
	int result = 17;

	result = 37 * result + this.getMeetingId();
	result = 37 * result + this.getUserId();
	return result;
    }

}
