package gr.ictpro.mall.model;

// Generated Aug 1, 2015 10:38:31 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification")
public class Notification implements java.io.Serializable {

    private Integer id;
    private String subject;
    private String message;
    private String module;
    private Date date;
    private byte[] parameters;
    private Boolean seen;
    private Integer handledBy;
    private Set<Role> roles = new HashSet<Role>(0);
    private Set<User> users = new HashSet<User>(0);

    public Notification() {
    }

    public Notification(String subject, String message, String module) {
	this.subject = subject;
	this.message = message;
	this.module = module;
    }

    public Notification(String subject, String message, String module, Date date, byte[] parameters, Boolean seen,
	    Integer handledBy, Set<Role> roles, Set<User> users) {
	this.subject = subject;
	this.message = message;
	this.module = module;
	this.date = date;
	this.parameters = parameters;
	this.seen = seen;
	this.handledBy = handledBy;
	this.roles = roles;
	this.users = users;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @Column(name = "subject", nullable = false, length = 100)
    public String getSubject() {
	return this.subject;
    }

    public void setSubject(String subject) {
	this.subject = subject;
    }

    @Column(name = "message", nullable = false, length = 65535, columnDefinition="Text")
    public String getMessage() {
	return this.message;
    }

    public void setMessage(String message) {
	this.message = message;
    }

    @Column(name = "module", nullable = false, length = 50)
    public String getModule() {
	return this.module;
    }

    public void setModule(String module) {
	this.module = module;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", length = 19)
    public Date getDate() {
	return this.date;
    }

    public void setDate(Date date) {
	this.date = date;
    }

    @Column(name = "parameters")
    public byte[] getParameters() {
	return this.parameters;
    }

    public void setParameters(byte[] parameters) {
	this.parameters = parameters;
    }

    @Column(name = "seen")
    public Boolean getSeen() {
	return this.seen;
    }

    public void setSeen(Boolean seen) {
	this.seen = seen;
    }

    @Column(name = "handled_by")
    public Integer getHandledBy() {
	return this.handledBy;
    }

    public void setHandledBy(Integer handledBy) {
	this.handledBy = handledBy;
    }

    @ManyToMany(mappedBy = "notifications")
    public Set<Role> getRoles() {
	return this.roles;
    }

    public void setRoles(Set<Role> roles) {
	this.roles = roles;
    }

    @ManyToMany(mappedBy = "notifications")
    public Set<User> getUsers() {
	return this.users;
    }

    public void setUsers(Set<User> users) {
	this.users = users;
    }

}
