package gr.ictpro.mall.model;

// Generated Feb 16, 2015 11:39:42 AM by Hibernate Tools 4.0.0

import gr.ictpro.mall.interceptors.ClientReferenceClass;
import gr.ictpro.mall.model.User;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.springframework.flex.core.io.AmfIgnore;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile")
@ClientReferenceClass(className="gr.ictpro.mall.client.model.vo.User")
public class Profile implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = -8146741979101829960L;
   
    private int userId;
    private User user;
    private String name;
    private byte[] photo;
    private Integer color;
    private Language language;

    public Profile() {
    }

    public Profile(User user, Language language, String name) {
	this.user = user;
	this.name = name;
	this.language = language;
    }

    public Profile(User user, Language language, String name, byte[] photo, Integer color) {
	this.user = user;
	this.name = name;
	this.photo = photo;
	this.color = color;
	this.language = language;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "user_id", unique = true, nullable = false)
    public int getUserId() {
	return this.userId;
    }

    public void setUserId(int userId) {
	this.userId = userId;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    @AmfIgnore
    public User getUser() {
	return this.user;
    }

    @AmfIgnore
    public void setUser(User user) {
	this.user = user;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "photo", columnDefinition = "MediumBlob")
    public byte[] getPhoto() {
	return this.photo;
    }

    public void setPhoto(byte[] photo) {
	this.photo = photo;
    }

    @Column(name = "color")
    public Integer getColor() {
	return this.color;
    }

    public void setColor(Integer color) {
	this.color = color;
    }
    
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "language_code", nullable = false)
    public Language getLanguage() {
	return this.language;
    }

    public void setLanguage(Language language) {
	this.language = language;
    }


}
