package gr.ictpro.mall.model;

// Generated Feb 16, 2015 11:39:42 AM by Hibernate Tools 4.0.0

import gr.ictpro.mall.model.hibernate.User;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.apache.commons.codec.binary.Base64;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile")
public class Profile implements java.io.Serializable {

    private int userId;
    private User user;
    private String name;
    private String photo;

    public Profile() {
    }

    public Profile(User user, String name) {
	this.user = user;
	this.name = name;
    }

    public Profile(User user, String name, byte[] photo) {
	this.user = user;
	this.name = name;
	this.photo = Base64.encodeBase64String(photo);
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "user_id", unique = true, nullable = false)
    public int getUserId() {
	return this.userId;
    }

    public void setUserId(int userId) {
	this.userId = userId;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public User getUser() {
	return this.user;
    }

    public void setUser(User user) {
	this.user = user;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }
    
    @Column(name = "photo")
    public byte[] getPhoto() {
	return Base64.decodeBase64(this.photo);
    }

    public void setPhoto(byte[] photo) {
	this.photo = Base64.encodeBase64String(photo);
    }
}
