package gr.ictpro.mall.model;

// Generated May 17, 2016 11:56:07 PM by Hibernate Tools 4.0.0

import gr.ictpro.mall.interceptors.ClientReferenceClass;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project")
@ClientReferenceClass(className="gr.ictpro.mall.client.model.vo.Project")
public class Project implements java.io.Serializable {

    private Integer id;
    private String name;
    private String notes;
    private Set<Course> courses = new HashSet<Course>(0);
    private Set<User> users = new HashSet<User>(0);

    public Project() {
    }

    public Project(String name) {
	this.name = name;
    }

    public Project(String name, String notes, Set<Course> courses, Set<User> users) {
	this.name = name;
	this.notes = notes;
	this.courses = courses;
	this.users = users;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "notes", length = 65535)
    public String getNotes() {
	return this.notes;
    }

    public void setNotes(String notes) {
	this.notes = notes;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "project")
    public Set<Course> getCourses() {
	return this.courses;
    }

    public void setCourses(Set<Course> courses) {
	this.courses = courses;
    }

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "project_user", joinColumns = {
	    @JoinColumn(name = "project_id", nullable = false, updatable = false) }, inverseJoinColumns = {
	    @JoinColumn(name = "user_id", nullable = false, updatable = false) })
    public Set<User> getUsers() {
	return this.users;
    }

    public void setUsers(Set<User> users) {
	this.users = users;
    }

}
