package gr.ictpro.mall.model;

// Generated Sep 5, 2014 11:12:49 PM by Hibernate Tools 4.0.0

import gr.ictpro.mall.interceptors.ClientReferenceClass;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.springframework.flex.core.io.AmfIgnore;
import org.springframework.security.core.GrantedAuthority;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role"
	, uniqueConstraints = @UniqueConstraint(columnNames = "role"))
@ClientReferenceClass(className="gr.ictpro.mall.client.model.vo.Role")
public class Role implements java.io.Serializable, GrantedAuthority {
    /**
     * 
     */
    private static final long serialVersionUID = -7911048899002478210L;
    
    private Integer id;
    private String role;
    private Set<User> users = new HashSet<User>(0);
    private Set<RoleNotification> roleNotifications = new HashSet<RoleNotification>(0);

    public Role() {
    }

    public Role(String role) {
	this.role = role;
    }

    public Role(String role, Set<User> users, Set<RoleNotification> roleNotifications) {
	this.role = role;
	this.users = users;
	this.roleNotifications = roleNotifications;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @Column(name = "role", unique = true, nullable = false, length = 45)
    public String getRole() {
	return this.role;
    }

    public void setRole(String role) {
	this.role = role;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "user_role", joinColumns = {
	    @JoinColumn(name = "role_id", nullable = false, updatable = false) }, inverseJoinColumns = {
	    @JoinColumn(name = "user_id", nullable = false, updatable = false) })
    @AmfIgnore
    public Set<User> getUsers() {
	return this.users;
    }

    @AmfIgnore
    public void setUsers(Set<User> users) {
	this.users = users;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
    @AmfIgnore
    public Set<RoleNotification> getRoleNotifications() {
	return this.roleNotifications;
    }

    @AmfIgnore
    public void setRoleNotifications(Set<RoleNotification> roleNotifications) {
	this.roleNotifications = roleNotifications;
    }

    @Override
    public boolean equals(Object obj) {
	if (this == obj)
	    return true;
	if (obj == null)
	    return false;
	if (getClass() != obj.getClass())
	    return false;
	Role other = (Role) obj;
	if (id == null) {
	    if (other.id != null)
		return false;
	} else if (!id.equals(other.id))
	    return false;
	return true;
    }

    @Override
    public String toString() {
	return role;
    }

    @Override
    @Transient
    @AmfIgnore
    public String getAuthority() {
	return getRole();
    }

}
