package gr.ictpro.mall.model;

// Generated Jan 9, 2016 5:28:52 PM by Hibernate Tools 4.0.0

import gr.ictpro.mall.interceptors.ClientReferenceClass;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "schedule")
@ClientReferenceClass(className="gr.ictpro.mall.client.model.vo.Schedule")
public class Schedule implements java.io.Serializable {

    private Integer id;
    private Classroom classroom;
    private Date startTime;
    private Date endTime;
    private int repeatInterval;
    private int day;
    private Date repeatUntil;
    private String description;
    private Set<Calendar> calendars = new HashSet<Calendar>(0);

    public Schedule() {
    }

    public Schedule(Classroom classroom, Date startTime, Date endTime, int repeatInterval, int day, Date repeatUntil, String description) {
	this.classroom = classroom;
	this.startTime = startTime;
	this.endTime = endTime;
	this.repeatInterval = repeatInterval;
	this.day = day;
	this.repeatUntil = repeatUntil;
	this.description = description;
    }

    public Schedule(Classroom classroom, Date startTime, Date endTime, int repeatInterval, int day, Date repeatUntil,
	    Set<Calendar> calendars, String description) {
	this.classroom = classroom;
	this.startTime = startTime;
	this.endTime = endTime;
	this.repeatInterval = repeatInterval;
	this.day = day;
	this.repeatUntil = repeatUntil;
	this.calendars = calendars;
	this.description = description;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "classroom_id", nullable = false)
    public Classroom getClassroom() {
	return this.classroom;
    }

    public void setClassroom(Classroom classroom) {
	this.classroom = classroom;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "start_time", nullable = false, length = 8)
    public Date getStartTime() {
	return this.startTime;
    }

    public void setStartTime(Date startTime) {
	this.startTime = startTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "end_time", nullable = false, length = 8)
    public Date getEndTime() {
	return this.endTime;
    }

    public void setEndTime(Date endTime) {
	this.endTime = endTime;
    }

    @Column(name = "repeat_interval", nullable = false)
    public int getRepeatInterval() {
	return this.repeatInterval;
    }

    public void setRepeatInterval(int repeatInterval) {
	this.repeatInterval = repeatInterval;
    }

    @Column(name = "day", nullable = false)
    public int getDay() {
	return this.day;
    }

    public void setDay(int day) {
	this.day = day;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "repeat_until", nullable = false, length = 10)
    public Date getRepeatUntil() {
	return this.repeatUntil;
    }

    public void setRepeatUntil(Date repeatUntil) {
	this.repeatUntil = repeatUntil;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "schedule")
    public Set<Calendar> getCalendars() {
	return this.calendars;
    }

    public void setCalendars(Set<Calendar> calendars) {
	this.calendars = calendars;
    }

    @Column(name = "description", nullable = false, length = 255)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }


}
