package gr.ictpro.mall.model;

// Generated Oct 3, 2015 2:40:56 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Translation generated by hbm2java
 */
@Entity
@Table(name = "translation")
public class Translation implements java.io.Serializable {

    private TranslationId id;
    private User user;
    private StudyClass studyClass;
    private EnglishText englishText;
    private String translatedText;

    public Translation() {
    }

    public Translation(TranslationId id, EnglishText englishText, String translatedText) {
	this.id = id;
	this.englishText = englishText;
	this.translatedText = translatedText;
    }

    public Translation(TranslationId id, User user, StudyClass studyClass, EnglishText englishText,
	    String translatedText) {
	this.id = id;
	this.user = user;
	this.studyClass = studyClass;
	this.englishText = englishText;
	this.translatedText = translatedText;
    }

    @EmbeddedId
    @AttributeOverrides({
	    @AttributeOverride(name = "languageCode", column = @Column(name = "language_code", nullable = false, length = 5)),
	    @AttributeOverride(name = "englishTextId", column = @Column(name = "english_text_id", nullable = false)) })
    public TranslationId getId() {
	return this.id;
    }

    public void setId(TranslationId id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    public User getUser() {
	return this.user;
    }

    public void setUser(User user) {
	this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "class_id")
    public StudyClass getStudyClass() {
	return this.studyClass;
    }

    public void setStudyClass(StudyClass studyClass) {
	this.studyClass = studyClass;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "english_text_id", nullable = false, insertable = false, updatable = false)
    public EnglishText getEnglishText() {
	return this.englishText;
    }

    public void setEnglishText(EnglishText englishText) {
	this.englishText = englishText;
    }

    @Column(name = "translated_text", nullable = false, length = 65535, columnDefinition="Text")
    public String getTranslatedText() {
	return this.translatedText;
    }

    public void setTranslatedText(String translatedText) {
	this.translatedText = translatedText;
    }

}
