package gr.ictpro.mall.model;

// Generated Dec 6, 2015 11:36:41 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TranslationId generated by hbm2java
 */
@Embeddable
public class TranslationId implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 4558670238125552900L;
    
    private int englishTextId;
    private String languageCode;
    private int classroomId;

    public TranslationId() {
    }

    public TranslationId(int englishTextId, String languageCode, int classroomId) {
	this.englishTextId = englishTextId;
	this.languageCode = languageCode;
	this.classroomId = classroomId;
    }

    @Column(name = "english_text_id", nullable = false)
    public int getEnglishTextId() {
	return this.englishTextId;
    }

    public void setEnglishTextId(int englishTextId) {
	this.englishTextId = englishTextId;
    }

    @Column(name = "language_code", nullable = false, length = 5)
    public String getLanguageCode() {
	return this.languageCode;
    }

    public void setLanguageCode(String languageCode) {
	this.languageCode = languageCode;
    }

    @Column(name = "classroom_id", nullable = false)
    public int getClassroomId() {
	return this.classroomId;
    }

    public void setClassroomId(int classroomId) {
	this.classroomId = classroomId;
    }

    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof TranslationId))
	    return false;
	TranslationId castOther = (TranslationId) other;

	return (this.getEnglishTextId() == castOther.getEnglishTextId())
		&& ((this.getLanguageCode() == castOther.getLanguageCode()) || (this.getLanguageCode() != null
			&& castOther.getLanguageCode() != null && this.getLanguageCode().equals(
			castOther.getLanguageCode())))
		&& (this.getClassroomId() == castOther.getClassroomId());
    }

    public int hashCode() {
	int result = 17;

	result = 37 * result + this.getEnglishTextId();
	result = 37 * result + (getLanguageCode() == null ? 0 : this.getLanguageCode().hashCode());
	result = 37 * result + this.getClassroomId();
	return result;
    }

}
