package gr.ictpro.mall.model;

// Generated Oct 3, 2015 2:40:56 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TranslationId generated by hbm2java
 */
@Embeddable
public class TranslationId implements java.io.Serializable {

    private String languageCode;
    private int englishTextId;

    public TranslationId() {
    }

    public TranslationId(String languageCode, int englishTextId) {
	this.languageCode = languageCode;
	this.englishTextId = englishTextId;
    }

    @Column(name = "language_code", nullable = false, length = 5)
    public String getLanguageCode() {
	return this.languageCode;
    }

    public void setLanguageCode(String languageCode) {
	this.languageCode = languageCode;
    }

    @Column(name = "english_text_id", nullable = false)
    public int getEnglishTextId() {
	return this.englishTextId;
    }

    public void setEnglishTextId(int englishTextId) {
	this.englishTextId = englishTextId;
    }

    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof TranslationId))
	    return false;
	TranslationId castOther = (TranslationId) other;

	return ((this.getLanguageCode() == castOther.getLanguageCode()) || (this.getLanguageCode() != null
		&& castOther.getLanguageCode() != null && this.getLanguageCode().equals(castOther.getLanguageCode())))
		&& (this.getEnglishTextId() == castOther.getEnglishTextId());
    }

    public int hashCode() {
	int result = 17;

	result = 37 * result + (getLanguageCode() == null ? 0 : this.getLanguageCode().hashCode());
	result = 37 * result + this.getEnglishTextId();
	return result;
    }

}
