package gr.ictpro.mall.model.hibernate;

// Generated Jan 31, 2016 7:54:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calendar generated by hbm2java
 */
@Entity
@Table(name = "calendar")
public class Calendar implements java.io.Serializable {

    private Integer id;
    private Schedule schedule;
    private User user;
    private Classroom classroom;
    private Calendar calendar;
    private String description;
    private Date endTime;
    private Date startTime;
    private Set<Calendar> calendars = new HashSet<Calendar>(0);

    public Calendar() {
    }

    public Calendar(String description, Date endTime, Date startTime) {
	this.description = description;
	this.endTime = endTime;
	this.startTime = startTime;
    }

    public Calendar(Schedule schedule, User user, Classroom classroom, Calendar calendar, String description,
	    Date endTime, Date startTime, Set<Calendar> calendars) {
	this.schedule = schedule;
	this.user = user;
	this.classroom = classroom;
	this.calendar = calendar;
	this.description = description;
	this.endTime = endTime;
	this.startTime = startTime;
	this.calendars = calendars;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "schedule_id")
    public Schedule getSchedule() {
	return this.schedule;
    }

    public void setSchedule(Schedule schedule) {
	this.schedule = schedule;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    public User getUser() {
	return this.user;
    }

    public void setUser(User user) {
	this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "classroom_id")
    public Classroom getClassroom() {
	return this.classroom;
    }

    public void setClassroom(Classroom classroom) {
	this.classroom = classroom;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "master_id")
    public Calendar getCalendar() {
	return this.calendar;
    }

    public void setCalendar(Calendar calendar) {
	this.calendar = calendar;
    }

    @Column(name = "description", nullable = false)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time", nullable = false, length = 19)
    public Date getEndTime() {
	return this.endTime;
    }

    public void setEndTime(Date endTime) {
	this.endTime = endTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time", nullable = false, length = 19)
    public Date getStartTime() {
	return this.startTime;
    }

    public void setStartTime(Date startTime) {
	this.startTime = startTime;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "calendar")
    public Set<Calendar> getCalendars() {
	return this.calendars;
    }

    public void setCalendars(Set<Calendar> calendars) {
	this.calendars = calendars;
    }

}
