package gr.ictpro.mall.model.hibernate;

// Generated Jan 31, 2016 7:54:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Classroomgroup generated by hbm2java
 */
@Entity
@Table(name = "classroomgroup")
public class Classroomgroup implements java.io.Serializable {

    private Integer id;
    private String name;
    private String notes;
    private Set<Classroom> classrooms = new HashSet<Classroom>(0);

    public Classroomgroup() {
    }

    public Classroomgroup(String name) {
	this.name = name;
    }

    public Classroomgroup(String name, String notes, Set<Classroom> classrooms) {
	this.name = name;
	this.notes = notes;
	this.classrooms = classrooms;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "notes", length = 65535)
    public String getNotes() {
	return this.notes;
    }

    public void setNotes(String notes) {
	this.notes = notes;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "classroom_classroomgroup", joinColumns = {
	    @JoinColumn(name = "group_id", nullable = false, updatable = false) }, inverseJoinColumns = {
	    @JoinColumn(name = "classroom_id", nullable = false, updatable = false) })
    public Set<Classroom> getClassrooms() {
	return this.classrooms;
    }

    public void setClassrooms(Set<Classroom> classrooms) {
	this.classrooms = classrooms;
    }

}
