package gr.ictpro.mall.model.hibernate;

// Generated Jan 31, 2016 7:54:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Classroom generated by hbm2java
 */
@Entity
@Table(name = "classroom"
	, uniqueConstraints = @UniqueConstraint(columnNames = { "name", "language_code" }))
public class Classroom implements java.io.Serializable {

    private Integer id;
    private Language language;
    private User user;
    private String name;
    private String notes;
    private Boolean forceUiLanguage;
    private Set<EmailTranslation> emailTranslations = new HashSet<EmailTranslation>(0);
    private Set<Classroomgroup> classroomgroups = new HashSet<Classroomgroup>(0);
    private Set<Translation> translations = new HashSet<Translation>(0);
    private Set<Schedule> schedules = new HashSet<Schedule>(0);
    private Set<User> users = new HashSet<User>(0);
    private Set<Calendar> calendars = new HashSet<Calendar>(0);

    public Classroom() {
    }

    public Classroom(String name) {
	this.name = name;
    }

    public Classroom(Language language, User user, String name, String notes, Boolean forceUiLanguage,
	    Set<EmailTranslation> emailTranslations, Set<Classroomgroup> classroomgroups,
	    Set<Translation> translations, Set<Schedule> schedules, Set<User> users, Set<Calendar> calendars) {
	this.language = language;
	this.user = user;
	this.name = name;
	this.notes = notes;
	this.forceUiLanguage = forceUiLanguage;
	this.emailTranslations = emailTranslations;
	this.classroomgroups = classroomgroups;
	this.translations = translations;
	this.schedules = schedules;
	this.users = users;
	this.calendars = calendars;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "language_code")
    public Language getLanguage() {
	return this.language;
    }

    public void setLanguage(Language language) {
	this.language = language;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "teacher_id")
    public User getUser() {
	return this.user;
    }

    public void setUser(User user) {
	this.user = user;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "notes", length = 65535)
    public String getNotes() {
	return this.notes;
    }

    public void setNotes(String notes) {
	this.notes = notes;
    }

    @Column(name = "force_ui_language")
    public Boolean getForceUiLanguage() {
	return this.forceUiLanguage;
    }

    public void setForceUiLanguage(Boolean forceUiLanguage) {
	this.forceUiLanguage = forceUiLanguage;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "classroom")
    public Set<EmailTranslation> getEmailTranslations() {
	return this.emailTranslations;
    }

    public void setEmailTranslations(Set<EmailTranslation> emailTranslations) {
	this.emailTranslations = emailTranslations;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "classroom_classroomgroup", joinColumns = {
	    @JoinColumn(name = "classroom_id", nullable = false, updatable = false) }, inverseJoinColumns = {
	    @JoinColumn(name = "group_id", nullable = false, updatable = false) })
    public Set<Classroomgroup> getClassroomgroups() {
	return this.classroomgroups;
    }

    public void setClassroomgroups(Set<Classroomgroup> classroomgroups) {
	this.classroomgroups = classroomgroups;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "classroom")
    public Set<Translation> getTranslations() {
	return this.translations;
    }

    public void setTranslations(Set<Translation> translations) {
	this.translations = translations;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "classroom")
    public Set<Schedule> getSchedules() {
	return this.schedules;
    }

    public void setSchedules(Set<Schedule> schedules) {
	this.schedules = schedules;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "classroom_user", joinColumns = {
	    @JoinColumn(name = "class_id", nullable = false, updatable = false) }, inverseJoinColumns = {
	    @JoinColumn(name = "user_id", nullable = false, updatable = false) })
    public Set<User> getUsers() {
	return this.users;
    }

    public void setUsers(Set<User> users) {
	this.users = users;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "classroom")
    public Set<Calendar> getCalendars() {
	return this.calendars;
    }

    public void setCalendars(Set<Calendar> calendars) {
	this.calendars = calendars;
    }

}
