package gr.ictpro.mall.model.hibernate;

// Generated Jan 31, 2016 7:54:21 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmailTranslation generated by hbm2java
 */
@Entity
@Table(name = "email_translation"
	, uniqueConstraints = @UniqueConstraint(columnNames = { "classroom_id", "language_code", "email_type" }))
public class EmailTranslation implements java.io.Serializable {

    private EmailTranslationId id;
    private Classroom classroom;
    private EnglishEmail englishEmail;
    private Language language;
    private String body;
    private String subject;

    public EmailTranslation() {
    }

    public EmailTranslation(EmailTranslationId id, Classroom classroom, EnglishEmail englishEmail, Language language,
	    String body, String subject) {
	this.id = id;
	this.classroom = classroom;
	this.englishEmail = englishEmail;
	this.language = language;
	this.body = body;
	this.subject = subject;
    }

    @EmbeddedId
    @AttributeOverrides({
	    @AttributeOverride(name = "classroomId", column = @Column(name = "classroom_id", nullable = false)),
	    @AttributeOverride(name = "emailType", column = @Column(name = "email_type", nullable = false)),
	    @AttributeOverride(name = "languageCode", column = @Column(name = "language_code", nullable = false, length = 5)) })
    public EmailTranslationId getId() {
	return this.id;
    }

    public void setId(EmailTranslationId id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "classroom_id", nullable = false, insertable = false, updatable = false)
    public Classroom getClassroom() {
	return this.classroom;
    }

    public void setClassroom(Classroom classroom) {
	this.classroom = classroom;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "email_type", nullable = false, insertable = false, updatable = false)
    public EnglishEmail getEnglishEmail() {
	return this.englishEmail;
    }

    public void setEnglishEmail(EnglishEmail englishEmail) {
	this.englishEmail = englishEmail;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "language_code", nullable = false, insertable = false, updatable = false)
    public Language getLanguage() {
	return this.language;
    }

    public void setLanguage(Language language) {
	this.language = language;
    }

    @Column(name = "body", nullable = false, length = 65535)
    public String getBody() {
	return this.body;
    }

    public void setBody(String body) {
	this.body = body;
    }

    @Column(name = "subject", nullable = false, length = 100)
    public String getSubject() {
	return this.subject;
    }

    public void setSubject(String subject) {
	this.subject = subject;
    }

}
