package gr.ictpro.mall.model.hibernate;

// Generated Jan 31, 2016 7:54:21 PM by Hibernate Tools 4.0.0

import gr.ictpro.mall.model.EmailType;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmailTranslationId generated by hbm2java
 */
@Embeddable
public class EmailTranslationId implements java.io.Serializable {

    private int classroomId;
    private EmailType emailType;
    private String languageCode;

    public EmailTranslationId() {
    }

    public EmailTranslationId(int classroomId, EmailType emailType, String languageCode) {
	this.classroomId = classroomId;
	this.emailType = emailType;
	this.languageCode = languageCode;
    }

    @Column(name = "classroom_id", nullable = false)
    public int getClassroomId() {
	return this.classroomId;
    }

    public void setClassroomId(int classroomId) {
	this.classroomId = classroomId;
    }

    @Column(name = "email_type", nullable = false)
    public EmailType getEmailType() {
	return this.emailType;
    }

    public void setEmailType(EmailType emailType) {
	this.emailType = emailType;
    }

    @Column(name = "language_code", nullable = false, length = 5)
    public String getLanguageCode() {
	return this.languageCode;
    }

    public void setLanguageCode(String languageCode) {
	this.languageCode = languageCode;
    }

    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof EmailTranslationId))
	    return false;
	EmailTranslationId castOther = (EmailTranslationId) other;

	return (this.getClassroomId() == castOther.getClassroomId())
		&& ((this.getEmailType() == castOther.getEmailType()) || (this.getEmailType() != null
			&& castOther.getEmailType() != null && this.getEmailType().equals(castOther.getEmailType())))
		&& ((this.getLanguageCode() == castOther.getLanguageCode()) || (this.getLanguageCode() != null
			&& castOther.getLanguageCode() != null && this.getLanguageCode().equals(
			castOther.getLanguageCode())));
    }

    public int hashCode() {
	int result = 17;

	result = 37 * result + this.getClassroomId();
	result = 37 * result + (getEmailType() == null ? 0 : this.getEmailType().hashCode());
	result = 37 * result + (getLanguageCode() == null ? 0 : this.getLanguageCode().hashCode());
	return result;
    }

}
