package gr.ictpro.mall.model.hibernate;

// Generated Jan 31, 2016 7:54:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language")
public class Language implements java.io.Serializable {

    private String code;
    private String englishName;
    private String localName;
    private Set<EmailTranslation> emailTranslations = new HashSet<EmailTranslation>(0);
    private Set<Classroom> classrooms = new HashSet<Classroom>(0);
    private Set<Translation> translations = new HashSet<Translation>(0);

    public Language() {
    }

    public Language(String code, String englishName, String localName) {
	this.code = code;
	this.englishName = englishName;
	this.localName = localName;
    }

    public Language(String code, String englishName, String localName, Set<EmailTranslation> emailTranslations,
	    Set<Classroom> classrooms, Set<Translation> translations) {
	this.code = code;
	this.englishName = englishName;
	this.localName = localName;
	this.emailTranslations = emailTranslations;
	this.classrooms = classrooms;
	this.translations = translations;
    }

    @Id
    @Column(name = "code", unique = true, nullable = false, length = 5)
    public String getCode() {
	return this.code;
    }

    public void setCode(String code) {
	this.code = code;
    }

    @Column(name = "english_name", nullable = false, length = 100)
    public String getEnglishName() {
	return this.englishName;
    }

    public void setEnglishName(String englishName) {
	this.englishName = englishName;
    }

    @Column(name = "local_name", nullable = false, length = 100)
    public String getLocalName() {
	return this.localName;
    }

    public void setLocalName(String localName) {
	this.localName = localName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
    public Set<EmailTranslation> getEmailTranslations() {
	return this.emailTranslations;
    }

    public void setEmailTranslations(Set<EmailTranslation> emailTranslations) {
	this.emailTranslations = emailTranslations;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
    public Set<Classroom> getClassrooms() {
	return this.classrooms;
    }

    public void setClassrooms(Set<Classroom> classrooms) {
	this.classrooms = classrooms;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
    public Set<Translation> getTranslations() {
	return this.translations;
    }

    public void setTranslations(Set<Translation> translations) {
	this.translations = translations;
    }

}
