package gr.ictpro.mall.model.hibernate;

// Generated Jan 31, 2016 7:54:21 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile")
public class Profile implements java.io.Serializable {

    private int userId;
    private User user;
    private Integer color;
    private String name;
    private byte[] photo;

    public Profile() {
    }

    public Profile(User user, String name) {
	this.user = user;
	this.name = name;
    }

    public Profile(User user, Integer color, String name, byte[] photo) {
	this.user = user;
	this.color = color;
	this.name = name;
	this.photo = photo;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "user_id", unique = true, nullable = false)
    public int getUserId() {
	return this.userId;
    }

    public void setUserId(int userId) {
	this.userId = userId;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public User getUser() {
	return this.user;
    }

    public void setUser(User user) {
	this.user = user;
    }

    @Column(name = "color")
    public Integer getColor() {
	return this.color;
    }

    public void setColor(Integer color) {
	this.color = color;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "photo")
    public byte[] getPhoto() {
	return this.photo;
    }

    public void setPhoto(byte[] photo) {
	this.photo = photo;
    }

}
