package gr.ictpro.mall.model.hibernate;

// Generated Sep 29, 2015 8:16:06 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoleNotificationId generated by hbm2java
 */
@Embeddable
public class RoleNotificationId implements java.io.Serializable {

    private int notificationId;
    private int roleId;

    public RoleNotificationId() {
    }

    public RoleNotificationId(int notificationId, int roleId) {
	this.notificationId = notificationId;
	this.roleId = roleId;
    }

    @Column(name = "notification_id", nullable = false)
    public int getNotificationId() {
	return this.notificationId;
    }

    public void setNotificationId(int notificationId) {
	this.notificationId = notificationId;
    }

    @Column(name = "role_id", nullable = false)
    public int getRoleId() {
	return this.roleId;
    }

    public void setRoleId(int roleId) {
	this.roleId = roleId;
    }

    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof RoleNotificationId))
	    return false;
	RoleNotificationId castOther = (RoleNotificationId) other;

	return (this.getNotificationId() == castOther.getNotificationId())
		&& (this.getRoleId() == castOther.getRoleId());
    }

    public int hashCode() {
	int result = 17;

	result = 37 * result + this.getNotificationId();
	result = 37 * result + this.getRoleId();
	return result;
    }

}
