package gr.ictpro.mall.model.hibernate;

// Generated Jan 31, 2016 7:54:21 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Translation generated by hbm2java
 */
@Entity
@Table(name = "translation")
public class Translation implements java.io.Serializable {

    private TranslationId id;
    private Classroom classroom;
    private EnglishText englishText;
    private Language language;
    private String translatedText;

    public Translation() {
    }

    public Translation(TranslationId id, Classroom classroom, EnglishText englishText, Language language,
	    String translatedText) {
	this.id = id;
	this.classroom = classroom;
	this.englishText = englishText;
	this.language = language;
	this.translatedText = translatedText;
    }

    @EmbeddedId
    @AttributeOverrides({
	    @AttributeOverride(name = "classroomId", column = @Column(name = "classroom_id", nullable = false)),
	    @AttributeOverride(name = "englishTextId", column = @Column(name = "english_text_id", nullable = false)),
	    @AttributeOverride(name = "languageCode", column = @Column(name = "language_code", nullable = false, length = 5)) })
    public TranslationId getId() {
	return this.id;
    }

    public void setId(TranslationId id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "classroom_id", nullable = false, insertable = false, updatable = false)
    public Classroom getClassroom() {
	return this.classroom;
    }

    public void setClassroom(Classroom classroom) {
	this.classroom = classroom;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "english_text_id", nullable = false, insertable = false, updatable = false)
    public EnglishText getEnglishText() {
	return this.englishText;
    }

    public void setEnglishText(EnglishText englishText) {
	this.englishText = englishText;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "language_code", nullable = false, insertable = false, updatable = false)
    public Language getLanguage() {
	return this.language;
    }

    public void setLanguage(Language language) {
	this.language = language;
    }

    @Column(name = "translated_text", nullable = false, length = 65535)
    public String getTranslatedText() {
	return this.translatedText;
    }

    public void setTranslatedText(String translatedText) {
	this.translatedText = translatedText;
    }

}
