package gr.ictpro.mall.model.hibernate;

// Generated Jan 31, 2016 7:54:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user"
	, uniqueConstraints = { @UniqueConstraint(columnNames = "email"), @UniqueConstraint(columnNames = "username") })
public class User implements java.io.Serializable {

    private Integer id;
    private String email;
    private boolean enabled;
    private String password;
    private String username;
    private Profile profile;
    private Set<Schedule> schedules = new HashSet<Schedule>(0);
    private Set<Calendar> calendars = new HashSet<Calendar>(0);
    private Set<UserNotification> userNotifications = new HashSet<UserNotification>(0);
    private Set<Classroom> classrooms = new HashSet<Classroom>(0);
    private Set<Classroom> classrooms_1 = new HashSet<Classroom>(0);
    private Set<Role> roles = new HashSet<Role>(0);
    private Set<Location> locations = new HashSet<Location>(0);
    private Set<RoleNotification> roleNotifications = new HashSet<RoleNotification>(0);

    public User() {
    }

    public User(String email, boolean enabled, String password, String username) {
	this.email = email;
	this.enabled = enabled;
	this.password = password;
	this.username = username;
    }

    public User(String email, boolean enabled, String password, String username, Profile profile,
	    Set<Schedule> schedules, Set<Calendar> calendars, Set<UserNotification> userNotifications,
	    Set<Classroom> classrooms, Set<Classroom> classrooms_1, Set<Role> roles, Set<Location> locations,
	    Set<RoleNotification> roleNotifications) {
	this.email = email;
	this.enabled = enabled;
	this.password = password;
	this.username = username;
	this.profile = profile;
	this.schedules = schedules;
	this.calendars = calendars;
	this.userNotifications = userNotifications;
	this.classrooms = classrooms;
	this.classrooms_1 = classrooms_1;
	this.roles = roles;
	this.locations = locations;
	this.roleNotifications = roleNotifications;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @Column(name = "email", unique = true, nullable = false, length = 45)
    public String getEmail() {
	return this.email;
    }

    public void setEmail(String email) {
	this.email = email;
    }

    @Column(name = "enabled", nullable = false)
    public boolean isEnabled() {
	return this.enabled;
    }

    public void setEnabled(boolean enabled) {
	this.enabled = enabled;
    }

    @Column(name = "password", nullable = false, length = 60)
    public String getPassword() {
	return this.password;
    }

    public void setPassword(String password) {
	this.password = password;
    }

    @Column(name = "username", unique = true, nullable = false, length = 20)
    public String getUsername() {
	return this.username;
    }

    public void setUsername(String username) {
	this.username = username;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
    public Profile getProfile() {
	return this.profile;
    }

    public void setProfile(Profile profile) {
	this.profile = profile;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<Schedule> getSchedules() {
	return this.schedules;
    }

    public void setSchedules(Set<Schedule> schedules) {
	this.schedules = schedules;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<Calendar> getCalendars() {
	return this.calendars;
    }

    public void setCalendars(Set<Calendar> calendars) {
	this.calendars = calendars;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<UserNotification> getUserNotifications() {
	return this.userNotifications;
    }

    public void setUserNotifications(Set<UserNotification> userNotifications) {
	this.userNotifications = userNotifications;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "classroom_user", joinColumns = {
	    @JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
	    @JoinColumn(name = "class_id", nullable = false, updatable = false) })
    public Set<Classroom> getClassrooms() {
	return this.classrooms;
    }

    public void setClassrooms(Set<Classroom> classrooms) {
	this.classrooms = classrooms;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<Classroom> getClassrooms_1() {
	return this.classrooms_1;
    }

    public void setClassrooms_1(Set<Classroom> classrooms_1) {
	this.classrooms_1 = classrooms_1;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "user_role", joinColumns = {
	    @JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
	    @JoinColumn(name = "role_id", nullable = false, updatable = false) })
    public Set<Role> getRoles() {
	return this.roles;
    }

    public void setRoles(Set<Role> roles) {
	this.roles = roles;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "location_user", joinColumns = {
	    @JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
	    @JoinColumn(name = "location_id", nullable = false, updatable = false) })
    public Set<Location> getLocations() {
	return this.locations;
    }

    public void setLocations(Set<Location> locations) {
	this.locations = locations;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<RoleNotification> getRoleNotifications() {
	return this.roleNotifications;
    }

    public void setRoleNotifications(Set<RoleNotification> roleNotifications) {
	this.roleNotifications = roleNotifications;
    }

}
